// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeNrFCQjitZM87iSO3kA_UzKrTcRQuRkc',
    appId: '1:817839298426:web:9af160100c1a20e61c28c3',
    messagingSenderId: '817839298426',
    projectId: 'work-force-kerala',
    authDomain: 'work-force-kerala.firebaseapp.com',
    storageBucket: 'work-force-kerala.appspot.com',
    measurementId: 'G-J3NMVX4L9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SmMYLyRsdouIqHyjEcVWyaoKp0Qw_fk',
    appId: '1:817839298426:android:581717f6df30f4e91c28c3',
    messagingSenderId: '817839298426',
    projectId: 'work-force-kerala',
    storageBucket: 'work-force-kerala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-_dEbLK85JBDs4vQkMvP6nP0Itcbpdc',
    appId: '1:817839298426:ios:3288ee79e1a8ea5c1c28c3',
    messagingSenderId: '817839298426',
    projectId: 'work-force-kerala',
    storageBucket: 'work-force-kerala.appspot.com',
    iosBundleId: 'com.example.workforceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-_dEbLK85JBDs4vQkMvP6nP0Itcbpdc',
    appId: '1:817839298426:ios:3288ee79e1a8ea5c1c28c3',
    messagingSenderId: '817839298426',
    projectId: 'work-force-kerala',
    storageBucket: 'work-force-kerala.appspot.com',
    iosBundleId: 'com.example.workforceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeNrFCQjitZM87iSO3kA_UzKrTcRQuRkc',
    appId: '1:817839298426:web:a53d3d15c29a68631c28c3',
    messagingSenderId: '817839298426',
    projectId: 'work-force-kerala',
    authDomain: 'work-force-kerala.firebaseapp.com',
    storageBucket: 'work-force-kerala.appspot.com',
    measurementId: 'G-KHM71VJDSC',
  );
}
